#!/bin/bash

FOLDER="$1"
ACTION="${2:-test}"
OPT=""
if [ "$ACTION" = "submit" ]; then
    OPT="-u"
fi

if [ "$ACTION" = "gen" ]; then
    atcoder-tools "$ACTION" "$FOLDER"
else
    (
        cd "$FOLDER"
        g++ sol.cc -o a.out
        atcoder-tools "$ACTION" $OPT
    )
fi
