#!/usr/bin/env python

import sys, os

if sys.argv[1][-1] == '.':
    name = sys.argv[1] + '_'.join(sys.argv[2:]) + '.py'
else:
    name = '_'.join(sys.argv[1:]) + '.py'

if not os.path.exists(name):
	with open(name, 'w'): pass
	os.chmod(name, 0o755)
	print(name)
